start /WAIT tools\quickbms.exe "tools\POD6.bms" tools\PODS\COMMON.POD tools\Modding\COMMON 
start /WAIT tools\quickbms.exe "tools\POD6.bms" tools\PODS\LANGUAGE.POD tools\Modding\LANGUAGE 
start /WAIT tools\quickbms.exe "tools\POD6.bms" tools\PODS\PATCH.POD tools\Modding\PATCH 
start /WAIT tools\quickbms.exe "tools\POD6.bms" tools\PODS\W64ART.POD tools\Modding\W64ART 
start /WAIT tools\quickbms.exe "tools\POD6.bms" tools\PODS\W64ART02.POD tools\Modding\W64ART02 
start /WAIT tools\quickbms.exe "tools\POD6.bms" tools\PODS\W64ENSND.POD tools\Modding\W64ENSND 
start /WAIT tools\quickbms.exe "tools\POD6.bms" tools\PODS\W64MODEL.POD tools\Modding\W64MODEL 
start /WAIT tools\quickbms.exe "tools\POD6.bms" tools\PODS\W64MUSND.POD tools\Modding\W64MUSND 
start /WAIT tools\quickbms.exe "tools\POD6.bms" tools\PODS\W64SET.POD tools\Modding\W64SET 
start /WAIT tools\quickbms.exe "tools\POD6.bms" tools\PODS\W64SOUND.POD tools\Modding\W64SOUND 